language: cpp
dist: xenial
sudo: false
compiler: gcc
os: linux

env: COMPILER=g++ CODE_COVERAGE=true CMAKE_BUILD_TYPE=Debug

cache: # see https://docs.travis-ci.com/user/caching/
  - directories:
      - $HOME/.cache

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y lcov
  - sudo apt-get install -qq -y ruby
  - sudo gem install coveralls-lcov
  - export CXX="${COMPILER}"

before_script:
  - ${CXX} --version
  - cmake --version
  - lcov --version
  - gcov --version

script:
  - cmake -DCMAKE_CXX_COMPILER=${CXX} -DCMAKE_BUILD_TYPE=Debug -DARCH=x86 -DCODE_COVERAGE=true -DCMAKE_CXX_FLAGS="-g -O0 -fprofile-arcs -ftest-coverage --coverage" . || exit 1
  - cmake --build cmake-build-debug -- -j2 || exit 1
  - ctest -j $(nproc) --output-on-failure || exit 1

after_success:
  # Create lcov report
  - lcov --capture --directory cmake-build-debug --output-file coverage.info --gcov-tool gcov-5
  - lcov --remove coverage.info '/usr/*' 'test/*' --output-file coverage.info
  - lcov --list coverage.info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"