language: cpp
compiler: clang
os: linux
dist: xenial

cache: # see https://docs.travis-ci.com/user/caching/
  - directories:
      - $HOME/.cache

addons:
  apt:
    packages:
      - gcov
      - lcov

script:
  - ./build.sh

after_success:
  # Create lcov report
  #  - lcov --capture --directory build --output-file coverage.info --debug
  #  - lcov --remove coverage.info '/usr/*' --output-file coverage.info --debug
  #  - lcov --remove coverage.info '*/test/*' --output-file coverage.info --debug
  #  - lcov --list coverage.info --debug
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"