language: cpp
compiler: clang
os: linux
dist: xenial

cache: # see https://docs.travis-ci.com/user/caching/
  - directories:
      - $HOME/.cache

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc-5 g++-5
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 60
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 60
  - sudo apt-get install -qq -y lcov
  - sudo apt-get install -qq -y ruby
  - sudo gem install coveralls-lcov

script:
  - ./build.sh

after_success:
  # Create lcov report
  - lcov --capture --directory build --output-file coverage.info --debug
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info --debug
  - lcov --remove coverage.info '*/test/*' --output-file coverage.info --debug
  - lcov --list coverage.info --debug
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"