language: cpp
dist: trusty
sudo: false
compiler: clang
os: linux

env: COMPILER=clang++-8 CODE_COVERAGE=true CMAKE_BUILD_TYPE=Debug

cache: # see https://docs.travis-ci.com/user/caching/
  - directories:
      - $HOME/.cache

addons:
  apt:
    packages: ["clang-8", "g++-6-multilib", "libc6-dbg", "libc6-dbg:i386", "linux-libc-dev", "linux-libc-dev:i386", "g++-6", "valgrind"]
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-8

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y lcov
  - sudo apt-get install -qq -y ruby
  - sudo gem install coveralls-lcov
  - export CXX="${COMPILER}"

before_script:
  - ${CXX} --version
  - cmake --version
  - lcov --version
  - gcov --version

script:
  - cmake -DCMAKE_CXX_COMPILER=${CXX} -DCMAKE_BUILD_TYPE=Debug -DARCH=x86 -DCODE_COVERAGE=true -DCMAKE_CXX_FLAGS="-g -O0 -fprofile-arcs -ftest-coverage --coverage" . || exit 1
  - cmake --build . -- -j2 || exit 1
  - ctest -j $(nproc) --output-on-failure || exit 1

after_success:
  # Create lcov report
  - lcov --capture --directory . --output-file coverage.info --debug --gcov-tool gcov-6
  - lcov --remove coverage.info '/usr/*' 'test/*' --output-file coverage.info --debug
  - lcov --list coverage.info --debug
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"